# Dockerfile.dev

FROM node:22-alpine

# yarn 설치
RUN apk add --no-cache yarn

# 작업 디렉토리 설정
WORKDIR /app

# 종속성 설치를 위한 package.json, yarn.lock 복사
COPY package*.json yarn.lock ./

# 종속성 설치
RUN yarn

# 소스 파일 복사
COPY . .

# 8765 포트 노출
EXPOSE 8765

# 개발 환경 실행 명령
CMD ["yarn", "dev"]
